server:
  port: 8081
spring:
  profiles:
    include:
cors:
  allow-headers: "X-Requested-With,Content-Type,Cookie,Accept,authorization,Authorization,credential,keyword,x-auth-token,iv,jsonFlag,timeStamp,random,range"
  allow-methods: "*"
  allow-expose: "x-auth-token,Content-Disposition"
  allow-credentials: "false"
  allow-origins: "*"
  allow-max-age: "3600"
httpMatchers:
  request: "/,/login,/logout,/user/register,/user/resetPassword,/oauth/**,/auth/**,/team/getByInviteKey,/team/checkInviteCode,/team/join,/team/getByInviteToken,/iterationFile/downloadFile,/iterationFile/img/**"
  web: "/hystrix.stream,/webjars/**,/resources/**,/swagger-ui.html,/swagger-resources/**,/v2/api-docs"

